### ISSUE TITLE
Support for RHEL

### ISSUE THREAD

**Issue by praveenuchiha** [cyberflow/chef-elasticsearch-curator#5]
Hi, Thank you for the cookbook, really appreciate it. Any plans to support RHEL (amazon AMI)? looks like it only supports debian for now. Thank you

**Comment by cyberflow** [comment]
Hello @praveenuchiha. Thank you. I haven't time right now for support RHEL. If you add it, I will be grateful to you.

**Comment by gmmurugan** [comment]
i will try to implement...

**Comment by GHostQC** [comment]
If you guys are interested, I just opened a pull request that may help resolve this issue. This is my first time actually using GitHub so I hope I'm doing this the right way. 

I needed this cookbook for a work project that runs on CentOS 7.2 so I tried to implement it the best I could. It's working for my project I'm working on but I don't know if it is really modular enough for this issue..

**Comment by cyberflow** [comment]
implement in #6 by @GHostQC
